### ISSUE TITLE
Dummy github release

### ISSUE THREAD

**Issue by hairmare** [savonet/ocaml-duppy#3]
Hi @toots 

Thank you for your hard work on ssl support and liquidsoap in general.

I it looks like you released `0.6.0` in https://github.com/savonet/ocaml-duppy/commit/ae21f5af518f3584730ac3ecb1c47dc14045b5fa or https://github.com/savonet/ocaml-duppy/commit/0b6983e04ea4629380171813743ddea031671e76 but haven't made a "Dummy github release" like [0.5.2](https://github.com/savonet/ocaml-duppy/releases/tag/0.5.2) yet.

I'm sure that's just an oversight on your part. Could I ask you to tag it proper? That would make building an RPM based on `0.6.0` much easier.

Thanks,
Lucas

**Comment by hairmare** [comment]
I realized you haven't added a release date in the changelog yet. Sorry for being a bother.

**Comment by toots** [comment]
Haha, yeah. No worries.

I've tied up this release with the next liquidsoap release. Are you using it outside of liquidsoap?

**Comment by hairmare** [comment]
Nah, I don't. 

I was trawling through my build files to get prepared for liquidsoap-next 😜
